security:
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: Oob0FmH8l5IkiIuMaHmbxA2SrO/6o3yiRCtIs4JS7ZWBHirzUZwxCWbSLVbGT+f3H8cqUIcta5hkWfmo/+LJgA==, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
                   id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
                    
        admin:
            pattern:    ^/
            form_login:
               check_path: /login_check
               login_path: /login
               provider: fos_userbundle
            logout:
              # provider: fos_userbundle
              # csrf_provider: form.csrf_provider
            logout: true
            anonymous: true


            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
                
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha512
        FOS\UserBundle\Model\UserInterface: sha512